import { createStore } from 'vuex'

export default createStore({
  state: {
    days: [
      {
        day: 1,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 2,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 3,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 4,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 5,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 6,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 7,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 8,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 9,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 10,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 11,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 12,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 13,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 14,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 15,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 16,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 17,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 18,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 19,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 20,
        eventYear: 2023,
        eventMonth: 'Березень',
        eventTime: '14:00-15:00',
        eventTimeLond: '12:00-13:00',
        event: 'Some event',
      },
      {
        day: 21,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 22,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 23,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 24,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 25,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 26,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 27,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 28,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 29,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 30,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
      {
        day: 31,
        eventYear: 2023,
        eventMonth: '',
        eventTime: '',
        event: '',
      },
    ],
    months: ['Січень','Лютий','Березень','Квітень','Травень','Червень','Липень','Серпень','Вересень','Жовтень','Листопад','Грудень']
  },
  getters: {
  },
  mutations: {
  },
  actions: {
  },
  modules: {
  }
})
